# Generated by Django 4.2.4 on 2023-10-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quests_complete', models.PositiveIntegerField(default=0)),
                ('quests_created', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.BooleanField(default=False)),
                ('feedback', models.CharField(default='Pending approval.', max_length=500)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.author')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('clue', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('long', models.DecimalField(decimal_places=14, max_digits=17)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.quest')),
            ],
        ),
    ]
