# Generated by Django 4.2.4 on 2023-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='answer',
            field=models.CharField(default='Answer not given.', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='Description not given.', max_length=400),
        ),
    ]
