# Generated by Django 4.2.4 on 2023-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location_answer_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
