# Generated by Django 4.2.4 on 2023-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_location_answer_alter_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='clue',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
