# Generated by Django 4.2.4 on 2023-11-06 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0005_author_completed_locations_author_completed_quests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='completed_locations',
        ),
        migrations.RemoveField(
            model_name='author',
            name='completed_quests',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_locations', models.ManyToManyField(blank=True, related_name='completed_by', to='maps.location')),
                ('completed_quests', models.ManyToManyField(blank=True, related_name='completed_by', to='maps.quest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
