# Generated by Django 4.2.4 on 2023-11-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_player_liked_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='quest',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
