# Generated by Django 4.2.4 on 2023-11-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_quest_ratings_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rated_quests',
            field=models.ManyToManyField(blank=True, related_name='rated_by', to='maps.quest'),
        ),
    ]
